# Generated by Django 5.1.4 on 2025-09-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
    ]
